version: "3.7"
services:

  #Laravel App
  app:
    build: .cloud/docker
    image: laravel-app
    depends_on:
      - mysql
      - redis
    volumes:
      - ./:/application
    depends_on: 
      - mysql

  #Nginx Service
  nginx:
    image: nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - .cloud/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./:/application
    depends_on: 
      - app

  #Mysl Service
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: root
    restart: always

  #Adminer
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8001:8080
    restart: always
    depends_on: 
      - mysql

#Volumes
volumes:
  db_data:
    driver: local